# Generated by Django 6.0.1 on 2026-02-14 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_page', to='common.page')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='OurCoreValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Value Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Value Text')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about/core_values/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='aboutus.aboutuspage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OurStorySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('story_text', models.TextField(blank=True, null=True, verbose_name='Story Description')),
                ('vision_text', models.TextField(blank=True, null=True, verbose_name='Vision Description')),
                ('mission_text', models.TextField(blank=True, null=True, verbose_name='Mission Description')),
                ('about_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_section', to='aboutus.aboutuspage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Member Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Member Image')),
                ('designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Member Designation')),
                ('domain', models.CharField(blank=True, max_length=150, null=True, verbose_name='Member Domain')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='aboutus.aboutuspage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
