# Generated by Django 6.0.1 on 2026-03-16 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to='common.page')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Banner Url')),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='banner/images', verbose_name='Banner Image')),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Alt Text')),
                ('desktop_video', models.FileField(blank=True, null=True, upload_to='banners/videos', verbose_name='Banner Video')),
                ('heading', models.CharField(blank=True, max_length=30, null=True, verbose_name='Banner Heading')),
                ('banner_text', models.CharField(blank=True, null=True, verbose_name='Banner Text')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='common.homepage')),
            ],
            options={
                'verbose_name': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home/features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_we_are', to='common.homepage')),
            ],
            options={
                'verbose_name': 'Who We Are Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/features/')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='common.homepage')),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'ordering': ['order'],
            },
        ),
    ]
