# Generated by Django 6.0.1 on 2026-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_homepage_banners_whowearesection_whychooseussection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseussection',
            name='text',
            field=models.TextField(),
        ),
    ]
