# Generated by Django 6.0.1 on 2026-02-20 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='NEET/JEE/LLB', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video Category',
                'verbose_name_plural': 'Video Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField(help_text='Paste YouTube video URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='yt/thumbnails/')),
                ('duration', models.CharField(help_text='Example: 15:30', max_length=10)),
                ('views', models.CharField(blank=True, help_text='125K views', max_length=50, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ytdata.videocategory')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_page', to='common.page')),
            ],
            options={
                'verbose_name': 'YouTube Page',
            },
        ),
        migrations.CreateModel(
            name='VideoStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(help_text='Videos, Views', max_length=100)),
                ('value', models.CharField(help_text='150+, 2M+', max_length=50)),
                ('icon', models.ImageField(upload_to='yt/staticon')),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ytdata.youtubepage')),
            ],
            options={
                'verbose_name': 'Video Statistic',
                'verbose_name_plural': 'Video Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='videocategory',
            name='video_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ytdata.youtubepage'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('playlist_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='ytdata.youtubepage')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['order'],
            },
        ),
    ]
