# Generated by Django 6.0.1 on 2026-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
