# Generated by Django 6.0.1 on 2026-02-19 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_page', to='common.page')),
            ],
            options={
                'verbose_name': 'Testimonial Page',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('course_college', models.CharField(help_text='B.Tech CSE, IIT Bombay', max_length=200, verbose_name='Cousre and College name')),
                ('batch', models.CharField(max_length=50, verbose_name='Batch')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/photo/', verbose_name='Student Photo')),
                ('review', models.TextField(verbose_name='Review Text')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Student rating out of 5', verbose_name='Rating (1–5)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('testimonial_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='testimonials.testimonialpage')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
