# Generated by Django 6.0.1 on 2026-02-19 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courses_page', to='common.page')),
            ],
            options={
                'verbose_name': 'Courses Page',
            },
        ),
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='NEET/JEE/LAW', max_length=150)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='courses/examcategory')),
                ('order', models.PositiveIntegerField(default=0)),
                ('courses_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_categories', to='courses.coursespage')),
            ],
            options={
                'verbose_name': 'Exam Category',
                'verbose_name_plural': 'Exam Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='MBBS/BDS/BHMS', max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('career_opportunities', models.TextField(help_text='Comma separated or paragraph format')),
                ('eligibility', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.examcategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NeedHelpSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='courses/needhelp')),
                ('courses_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_section', to='courses.coursespage')),
            ],
            options={
                'verbose_name': 'Need Help Section',
            },
        ),
        migrations.CreateModel(
            name='TopCollege',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('college_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='government', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_colleges', to='courses.examcategory')),
            ],
            options={
                'verbose_name': 'Top College',
                'verbose_name_plural': 'Top Colleges',
                'ordering': ['order'],
            },
        ),
    ]
