# Generated by Django 6.0.1 on 2026-03-21 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needhelpsection',
            name='courses_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_section', to='courses.coursespage'),
        ),
    ]
